MyProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
    path('',include('adminapp.urls')),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

adminapp/urls.py
from django.urls import path
from . import views
app_name='adminapp'
urlpatterns=[
    path('adminlogin/',views.adminlogin,name='adminlogin'),
    path('adminloginhome/1',views.adminloginhome,name='adminloginhome'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('delete1/<int:id>',views.delete1,name='delete1'),
    path('supdate/<int:id>',views.supdate,name='supdate'),
    path('acupdate/<int:id>',views.acupdate,name='acupdate'),
    path('addjob',views.addjob,name='addjob'),
    path('addteam',views.addteam,name='addteam'),
    path('jobdelete/<int:id>',views.jobdelete,name='jobdelete'),
    path('addcourse',views.addcourse,name='addcourse'),
    path('jobedit/<int:id>',views.jobedit,name='jobedit'),
    path('addreview',views.addreview,name='addreview'),
    path('teamedit/<int:id>',views.teamedit,name='teamedit'),
    path('teamdel/<int:id>',views.teamdel,name='teamdel'),
    path('courseedit/<int:id>',views.courseedit,name='courseedit'),
    path('coursedel/<int:id>',views.coursedel,name='coursedel'),
    path('reviewedit/<int:id>',views.reviewedit,name='reviewedit'),
    path('psedit/<int:id>',views.psedit,name='psedit'),
    path('revdel/<int:id>',views.revdel,name='revdel'),
]

app1/urls.py
from django.urls import path
from . import views
app_name='app1'
urlpatterns=[
    path('',views.index,name='index'),
    path('signup',views.signup,name='signup'),
    path('about',views.about,name='about'),
    path('service',views.service,name='service'),
    path('login',views.login,name='login'),
    path('loginhome/<int:id>',views.loginhome,name='loginhome'),
    path('signuphome',views.signuphome,name='signuphome'),
    path('careers',views.careers,name='careers'),
    path('careersignup',views.careersignup,name='careersignup'),
    path('clogin',views.clogin,name='clogin'),
    path('chome/<int:id>',views.chome,name='chome'),
    path('contact',views.contact,name='contact'),
    path('mail',views.mail,name='mail'),
    path('logout',views.logout,name='logout'),
    path('changepassword/<int:id>',views.changepassword,name='changepassword'),
    path('cupdate/<int:id>',views.cupdate,name='cupdate'),
]

app1/models.py
from django.db import models

# Create your models here.

# Client Service Signup
class ServiceSigup(models.Model):
    Name=models.CharField(max_length=16)
    Designation=models.CharField(max_length=16)
    CompanyName=models.CharField(max_length=20)
    ContactEmail=models.EmailField()
    ContactNumber=models.IntegerField()
    ServiceType=models.CharField(max_length=15)
    ServiceDetails=models.CharField(max_length=200)
    Password=models.CharField(max_length=8)

# Job seekers signup
class CareerSignup(models.Model):
    Name=models.CharField(max_length=16)
    Email=models.EmailField()
    ContactNumber=models.IntegerField()
    DOB=models.DateField()
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    Gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    Qualification=models.CharField(max_length=20)
    InstituteName=models.CharField(max_length=20)
    YearOfPassing=models.IntegerField()
    Password=models.CharField(max_length=8)

app1/forms.py
from django import forms
from .models import ServiceSigup,CareerSignup

# SIGNUPFORM for clients
class ServiceSignUpForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=6)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=6)
    class Meta():
        model=ServiceSigup
        fields='__all__'

# Login form for clients( service page login )
class ServiceLogInForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8)
    class Meta():
        model=ServiceSigup
        fields=('ContactEmail','Password')

# Career signup page
class CSignupForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=6)
    ConfirmPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=6)
    class Meta():
        model=CareerSignup
        fields='__all__'

# Login form for job seekers( career page login )
class CareerLogInForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=8)
    class Meta():
        model=CareerSignup
        fields=('Email','Password')

# changepassword for career
class ChangePassword(forms.Form):
    OldPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=6)
    NewPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=6)
    ConfirmNewPassword=forms.CharField(widget=forms.PasswordInput,max_length=8,min_length=6)

# Update for career
class CUpdateForm(forms.ModelForm):
    class Meta():
        model=CareerSignup
        fields=('Name','Email','ContactNumber',)

app1/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib import messages
from . forms import ServiceSignUpForm,ServiceLogInForm,CSignupForm,CareerLogInForm,ChangePassword,CUpdateForm
from adminapp.models import Job,Team,Course,Review,ProjectSummary
from . models import ServiceSigup,CareerSignup
from MyProject import settings
from django.core.mail import send_mail
from django.contrib.auth import logout as logouts


# Create your views here.

# index page
def index(request):
    team=Team.objects.all()
    course=Course.objects.all()
    review=Review.objects.all()
    project=ProjectSummary.objects.all()
    return render(request,'index.html',{'team':team,'course':course,'review':review,'project':project})
# end of index page

# register page
def signup(request):
    if request.method=='POST':
        form=ServiceSignUpForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data['Name']
            designation=form.cleaned_data['Designation']
            companyname=form.cleaned_data['CompanyName']
            contactemail=form.cleaned_data['ContactEmail']
            contactnumber=form.cleaned_data['ContactNumber']
            servicetype=form.cleaned_data['ServiceType']
            servicedetails=form.cleaned_data['ServiceDetails']
            password=form.cleaned_data['Password']
            cpassword=form.cleaned_data['ConfirmPassword']

            # Checking whether email exists or not
            user=ServiceSigup.objects.filter(ContactEmail=contactemail).exists()

            if user:
                messages.warning(request,"User exist")
                return redirect('/signup')

            elif password!=cpassword:
                messages.warning(request,"Password mismatch")
                return redirect('/signup')

            else:
                tab=ServiceSigup(Name=name,Designation=designation,CompanyName=companyname,ContactEmail=contactemail,ContactNumber=contactnumber,ServiceType=servicetype,ServiceDetails=servicedetails,Password=password)
                tab.save()
                messages.warning(request,"Signup Success")
                return redirect('/service')
    else:
        form=ServiceSignUpForm()
    return render(request,'signup.html',{'form':form})
# end of register page

# about page
def about(request):
    return render(request,'about.html')
# end of about page

# service page ( client )
def service(request):
    return render(request,'service.html')
#end of service page

# service login ( client )
def login(request):
    if request.method=='POST':
        form=ServiceLogInForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data['ContactEmail']
            password=form.cleaned_data['Password']

        try:
            # checking availablity of the user
            user=ServiceSigup.objects.get(ContactEmail=email)

            # checking whether the email exists or not
            if not user:
                messages.warning(request,"User does not exist")
                return redirect('/login')
            
            # checking whether the password is correct or not
            elif password!=user.Password:
                messages.warning(request,"Incorrect Password")
                return redirect('/login')
            
            else:
                messages.warning(request,"Login success")
                return redirect('/loginhome/%s'%user.id)
        except:
            messages.warning(request,"Email or password incorrect")
            return redirect('/login')
    else:
        form=ServiceLogInForm()
    return render(request,'login.html',{'form':form})

# client home
def loginhome(request,id):
    user=ServiceSigup.objects.get(id=id)
    return render(request,'loginhome.html',{'user':user})

# signup home
def signuphome(request):
    return render(request,'signuphome.html')

# careers page
def careers(request):
    return render(request,'careers.html')

# Career signup page
def careersignup(request):
    if request.method=='POST':
        form=CSignupForm(request.POST)
        if form.is_valid():
            name=form.cleaned_data['Name']
            email=form.cleaned_data['Email']
            cnumber=form.cleaned_data['ContactNumber']
            dob=form.cleaned_data['DOB']
            gender=form.cleaned_data['Gender']
            qualification=form.cleaned_data['Qualification']
            institutename=form.cleaned_data['InstituteName']
            yearofpass=form.cleaned_data['YearOfPassing']
            password=form.cleaned_data['Password']
            cpassword=form.cleaned_data['ConfirmPassword']
        try:
            # Checking whether email exists or not
            user=CareerSignup.objects.filter(Email=email).exists()

            if user:
                messages.warning(request,"User exist")
                return redirect('/careersignup')

            elif password!=cpassword:
                messages.warning(request,"Password mismatch")
                return redirect('/careersignup')

            else:
                tab=CareerSignup(Name=name,Email=email,ContactNumber=cnumber,DOB=dob,Gender=gender,Qualification=qualification,InstituteName=institutename,YearOfPassing=yearofpass,Password=password)
                tab.save()
                messages.warning(request,"Signup Success")
                return redirect('/careers')
        except:
            messages.warning(request,"Error on data..please double check")        
    else:
        form=CSignupForm()
    return render(request,'careersignup.html',{'form':form})

# Career login ( Job seekers )
def clogin(request):
    if request.method=='POST':
        form=CareerLogInForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data['Email']
            password=form.cleaned_data['Password']
        try:
            # checking availablity of the user
            user=CareerSignup.objects.get(Email=email)

            # checking whether the email exists or not
            if not user:
                messages.warning(request,"User does not exist")
                return redirect('/clogin')
            
            # checking whether the password is correct or not
            elif password!=user.Password:
                messages.warning(request,"Incorrect Password")
                return redirect('/clogin')
            
            else:
                messages.warning(request,"Login success")
                return redirect('/chome/%s'%user.id)
        except:
            messages.warning(request,"Email or password error")
    else:
        form=CareerLogInForm()
    return render(request,'clogin.html',{'form':form})

# career home
def chome(request,id):
    user=CareerSignup.objects.get(id=id)
    job=Job.objects.all()
    return render(request,'chome.html',{'user':user,'job':job})

# contact page
def contact(request):
    return render(request,'contact.html')

# mail
def mail(request):
    if request.method=='POST':
        cname=request.POST.get('contact_name')
        cemail=request.POST.get('contact_email')
        cmessage=request.POST.get('contact_message')
        toemail='amalraj0310@gmail.com'
        res = send_mail(cname,cmessage,settings.EMAIL_HOST_USER,[toemail],fail_silently=False)
        if(res==1):
            msg="Mail sent successfully"
        else:
            msg="Message could not sent"
        return HttpResponse(msg)
    else:
        return render(request,'index.html')

# logout
def logout(request):
    logouts(request)
    messages.warning(request,"Logout success")
    return redirect('/')

# change password for clients
def changepassword(request,id):
    user=CareerSignup.objects.get(id=id)
    if request.method=='POST':
        form=ChangePassword(request.POST)
        if form.is_valid():
            oldpassword=form.cleaned_data['OldPassword']
            newpassword=form.cleaned_data['NewPassword']
            confirmnewpassword=form.cleaned_data['ConfirmNewPassword']

            if oldpassword!=user.Password:
                messages.warning(request,"Incorrect Password")
                return redirect('/changepassword/%s'%user.id)
            elif oldpassword==newpassword:
                messages.warning(request,"Password not available")
                return redirect('/changepassword/%s'%user.id)
            elif newpassword!=confirmnewpassword:
                messages.warning(request,"Password Mismatch")
                return redirect('/changepassword/%s'%user.id)
            else:
                user.Password=newpassword
                user.save()
                messages.warning(request,"Success")
                return redirect('/clogin')
    else:
        form=ChangePassword()
    return render(request,'changepassword.html',{'form':form,'user':user})

# Update page for career
def cupdate(request,id):
    user=CareerSignup.objects.get(id=id)
    if request.method=='POST':
        form=CUpdateForm(request.POST or None, instance=user)
        if form.is_valid():
            form.save()
            messages.success(request,"Success")
            return redirect('/chome/%s'%user.id)
    else:
      form=CUpdateForm(instance=user)
    return render(request,'cupdate.html',{'form':form,'user':user})

app1/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">
    <title>MNC PORTFOLIO</title>

    <!-- Favicon -->
    <link href="img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Jost:wght@500;600;700&family=Open+Sans:wght@400;600&display=swap" rel="stylesheet"> 

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="{% static 'css/owl.carousel.min.css' %}" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <!-- Navbar Start -->
    <div class="container-fluid p-0">
        <nav class="navbar navbar-expand-lg bg-white navbar-light py-3 py-lg-0 px-lg-5">
            <a href="{% url 'app1:index' %}" class="navbar-brand ml-lg-3">
                <img src="{% static 'images/logo.png' %}" style="width: 100px;" alt="">
            </a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-between px-lg-3" id="navbarCollapse">
                <div class="navbar-nav mx-auto py-0">
                    <a href="{% url 'app1:index' %}" class="nav-item nav-link ">Home</a>
                    <a href="{% url 'app1:about' %}" class="nav-item nav-link">About</a>
                    <a href="{% url 'app1:service' %}" class="nav-item nav-link">Service</a>
                    <a href="{% url 'app1:careers' %}" class="nav-item nav-link">Career</a>
                    <a href="{% url 'app1:contact' %}" class="nav-item nav-link">Contact</a>
                </div>
            </div>
        </nav>
    </div>
    <!-- Navbar End -->
   

    {% block content %}

    {% endblock %}
   
    <!-- Footer Start -->
    <div class="container-fluid position-relative overlay-top bg-dark text-white-50 py-5">
        <div class="container mt-5 pt-5">
            <div class="row">
                <div class="col-md-6 mb-5">
                    <a href="{% url 'app1:index' %}" class="navbar-brand">
                        <h1 class="mt-n2 text-uppercase text-white"><img src="{% static 'images/logo.png' %}"  style="width: 100px;" alt="">INFINITE G ltd.</h1>
                    </a>
                    <p class="m-0">Shape the future of technology</p>
                </div>
                <div class="col-md-6 mb-5">
                    <form action="{% url 'app1:mail' %}" method="POST">
                        {% csrf_token %}
                    <h3 class="text-white mb-4">Feedbacks</h3>
                    <div class="w-100">
                        <div class="input-group">
                            <input type="text" class="form-control border-light" style="padding: 30px;" name="contact_message" placeholder="Feedbacks">
                            <div class="input-group-append">
                                <button class="btn btn-primary px-4">Send</button>
                            </div>
                        </div>
                    </div>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="col-md-4 mb-5">
                    <h3 class="text-white mb-4">Get In Touch</h3>
                    <p><i class="fa fa-map-marker-alt mr-2"></i>123 COMPLEX,ABC STREET,BANGALORE</p>
                    <p><i class="fa fa-phone-alt mr-2"></i>+123 3645631656</p>
                    <p><i class="fa fa-envelope mr-2"></i>infiniteglobal@contact.ac.in</p>
                    <div class="d-flex justify-content-start mt-4">
                        <a class="text-white mr-4" href="#"><i class="fab fa-2x fa-twitter"></i></a>
                        <a class="text-white mr-4" href="#"><i class="fab fa-2x fa-facebook-f"></i></a>
                        <a class="text-white mr-4" href="#"><i class="fab fa-2x fa-linkedin-in"></i></a>
                        <a class="text-white" href="#"><i class="fab fa-2x fa-instagram"></i></a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h3 class="text-white mb-4">Our Services</h3>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Web Development</a>
                        <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Apps Development</a>
                        <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Marketing</a>
                        <a class="text-white-50 mb-2" href="#"><i class="fa fa-angle-right mr-2"></i>Research</a>
                        <a class="text-white-50" href="#"><i class="fa fa-angle-right mr-2"></i>SEO</a>
                    </div>
                </div>
                <div class="col-md-4 mb-5">
                    <h3 class="text-white mb-4">Quick Links</h3>
                    <div class="d-flex flex-column justify-content-start">
                        <a class="text-white-50 mb-2" href="{% url 'app1:index' %}"><i class="fa fa-angle-right mr-2"></i>Home</a>
                        <a class="text-white-50 mb-2" href="{% url 'app1:about' %}"><i class="fa fa-angle-right mr-2"></i>About</a>
                        <a class="text-white-50 mb-2" href="{% url 'app1:service' %}"><i class="fa fa-angle-right mr-2"></i>Service</a>
                        <a class="text-white-50 mb-2" href="{% url 'app1:careers' %}"><i class="fa fa-angle-right mr-2"></i>Career</a>
                        <a class="text-white-50" href="{% url 'app1:contact' %}"><i class="fa fa-angle-right mr-2"></i>Contact</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid bg-dark text-white-50 border-top py-4" style="border-color: rgba(256, 256, 256, .1) !important;">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-center text-md-left mb-3 mb-md-0">
                    <p class="m-0">Copyright &copy; <a class="text-white" href="#">Infinity</a>. All Rights Reserved.
                    </p>
                </div>
                <div class="col-md-6 text-center text-md-right">
                    <p class="m-0">Designed by <a class="text-white" href="{% url 'adminapp:adminlogin' %}">Amalraj Karatt</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary rounded-0 btn-lg-square back-to-top"><i class="fa fa-angle-double-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

app1/templates/careersignup.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/careersgnp.css' %}">
</head>
<body>
    <div class="crr-body">
            <section class="career-sgnp">

      <header>Registration Form</header>
      <div class="sgnp-alt">
        {% for msg in messages %}
        {{msg}}
        {% endfor %}
        </div>
  
    <form class=" formi" action="" method="POST">
        {% csrf_token %}
        <div class="input-box">
    
    <label for="id_Name">Name</label>
    <input type="text" name="Name" maxlength="16" required id="id_Name" placeholder="Full Name">
        </div>
    
        <div class="input-box">

    <label for="id_Email">Email</label>
    <input type="email" name="Email" maxlength="254" required id="id_Email" placeholder="Email">
        </div>

        <div class="input-box">
    
    <label for="id_ContactNumber">Contact Number</label>
    <input type="number" name="ContactNumber" required id="id_ContactNumber" placeholder="Number">

        </div>     
        <div class="column">

            <div class="gender-box">
                <label for="id_Gender" style="color: #333;">Gender</label>
                <select name="Gender" required id="id_Gender" class="slt-box" style="border-radius: 6px;
                margin-top: 5px;
                padding: 0 105px;
                outline: none;
                font-size: 1rem;
                color: #707070;
                border: 1px solid #ddd;
                height: 55px;
                width: 19rem;">
                <option value="" selected>Gender</option>
                <option value="M">Male</option>
                <option value="F">Female</option>
                </select>
            </div>

        <div class="input-box">

    <label for="id_DOB">DOB</label>
    <input type="date" name="DOB" required id="id_DOB">

        </div>
        </div>



          <div class="input-box">
      
    <label for="id_Qualification">Qualification</label>
    <input type="text" name="Qualification" maxlength="20" required id="id_Qualification" placeholder="Qualification">

          </div>

        <div class="input-box">

    <label for="id_InstituteName">Institute  Name</label>    
    <input type="text" name="InstituteName" maxlength="20" required id="id_InstituteName" placeholder="Institue/University">

        </div>
    
        <div class="input-box">

    <label for="id_YearOfPassing">Year Of Passing</label>  
    <input type="number" name="YearOfPassing" required id="id_YearOfPassing" placeholder="Year Of Passing">
      
        </div>

        <div class="input-box">

    <label for="id_Password">Password</label> 
    <input type="password" name="Password" maxlength="8" minlength="6" required id="id_Password" placeholder="Password">

        </div>

        <div class="input-box">

    <label for="id_ConfirmPassword">Confirm Password</label>
    <input type="password" name="ConfirmPassword" maxlength="8" minlength="6" required id="id_ConfirmPassword" placeholder="Confirm Password">

        </div>

    <input  type="submit" class="submit-btn" value="Save">
    <p style="text-align: center;margin-top: 10px;font-size: 15px;">Already registered.? <a href="{% url 'app1:clogin' %}">Login</a></p>
    </form>

    </section>
    </div>

</body>
</html>
{% endblock %}

app1/templates/cupdate.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MNC PORTFOLIO</title>
    
    <!-- custom css file -->
    <link rel="stylesheet" href="{% static 'css/cpw.css' %}">
  </head>
 <body>

  <form class="formi" action="" method="POST">
    {% csrf_token %}
        <section class="container forms">
            <div class="form login">
                <div class="form-content">
                    <header>Update</header>
                    <form action="#">
                        <div class="field input-field">
                            <input type="text" name="Name" placeholder="{{user.Name}}"  required id="id_Name">
                        </div>

                        <div class="field input-field">
                            <input type="email" name="Email" placeholder="{{user.Email}}" required id="id_Email">
                           
                        </div>
                        <div class="field input-field">
                            <input type="number" name="ContactNumber" placeholder="{{user.ContactNumber}}" required id="id_ContactNumber">
                        </div>
                        <div class="alrt-msg">
                        {% for msg in messages %}
                        {{ msg }}
                        {% endfor %}

                        </div>

                        <div class="field button-field">
                          <input class="lg-btn"  type="submit" value="Save">

                        </div>
                    </form>
                </div>

            </div>
           
        </section>
      </form>

    </body>
</html>

app1/templates/signup.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MNC PORTFOLIO</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<!-- index page css -->
<link rel="stylesheet" href="{% static 'css/signup.css' %}">


</head>
<body>
    <div class="sgnp-full-body">
        <div class="col-sm-6">
             <div class="sgnp-body">
      <header>Registration Form</header>
      <div class="sgnp-alt">
      {% for msg in messages %}
      {{msg}}
      {% endfor %}
      </div>

      <form action="" class="formi" method="POST">
        {% csrf_token %}
        <div class="input-box">
            <label for="id_Name">Full Name</label>
            <input class="inpt" type="text" name="Name" maxlength="16" placeholder="Full Name" required id="id_Name">
        </div>

        <div class="input-box">
            <label for="id_Designation">Designation</label>        
        <input class="inpt" type="text" name="Designation" maxlength="16" required placeholder="Designation" id="id_Designation">
        </div>

        <div class="input-box">
            <label for="id_CompanyName">Company Name</label>
        <input class="inpt" type="text" name="CompanyName" maxlength="20" required placeholder="Company Name" id="id_CompanyName">
        </div>

        <div class="input-box">
            <label for="id_ContactEmail">Contact Email</label>
            <input class="inpt" type="email" name="ContactEmail" maxlength="254" placeholder="Contact Email" required id="id_ContactEmail">
        </div>

        <div class="input-box">
            <label for="id_ContactNumber">Contact Number</label>    
            <input class="inpt" type="number" name="ContactNumber" required placeholder="Contact Number" id="id_ContactNumber">
        </div>

        <div class="input-box">
            <label for="id_ServiceType">Service Type</label>
            <input class="inpt" type="text" name="ServiceType" maxlength="15" placeholder="Service Type" required id="id_ServiceType">                
        </div>

        <div class="input-box">
            <label for="id_ServiceDetails">Service Details</label>
            <input class="inpt" type="text" name="ServiceDetails" maxlength="200" placeholder="Service In Details" required id="id_ServiceDetails">
        </div>

        <div class="input-box">
            <label for="id_Password">Password</label>
            <input class="inpt" type="password" name="Password" maxlength="8" minlength="6" placeholder="Password" required id="id_Password">
        </div>

        <div class="input-box">
            <label for="id_ConfirmPassword">Confirm Password</label>
            <input class="inpt" type="password" name="ConfirmPassword" maxlength="8" minlength="6" placeholder="Confirm Password" required id="id_ConfirmPassword">
        </div>

        <input class="submit-btn" type="submit" value="Start Business">

      </form>
    </div>
        </div>
        <div class="col-sm-6">
            <img class="sgup-img" src="{% static 'images/img11.jpg'%}" alt="">
            <div class="smdl">
                <h2>
                    Connecting with the right team is the best step in business<br>
                    You are 1 step away from that
                </h2>
            </div>
            <div class="sgnup-lg">
                <h3>Already enqiured.?</h3><a class="sgnp-lgn" href="{% url 'app1:login' %}">Login</a>
            </div>
        </div>
       
    </div>
    
  </body>
</html>