MyProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app1.urls')),
    path('',include('adminapp.urls')),
]

urlpatterns+=staticfiles_urlpatterns()
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

adminapp/urls.py
from django.urls import path
from . import views
app_name='adminapp'
urlpatterns=[
    path('adminlogin/',views.adminlogin,name='adminlogin'),
    path('adminloginhome/1',views.adminloginhome,name='adminloginhome'),
    path('delete/<int:id>',views.delete,name='delete'),
    path('delete1/<int:id>',views.delete1,name='delete1'),
    path('supdate/<int:id>',views.supdate,name='supdate'),
    path('acupdate/<int:id>',views.acupdate,name='acupdate'),
    path('addjob',views.addjob,name='addjob'),
    path('addteam',views.addteam,name='addteam'),
    path('jobdelete/<int:id>',views.jobdelete,name='jobdelete'),
    path('addcourse',views.addcourse,name='addcourse'),
    path('jobedit/<int:id>',views.jobedit,name='jobedit'),
    path('addreview',views.addreview,name='addreview'),
    path('teamedit/<int:id>',views.teamedit,name='teamedit'),
    path('teamdel/<int:id>',views.teamdel,name='teamdel'),
    path('courseedit/<int:id>',views.courseedit,name='courseedit'),
    path('coursedel/<int:id>',views.coursedel,name='coursedel'),
    path('reviewedit/<int:id>',views.reviewedit,name='reviewedit'),
    path('psedit/<int:id>',views.psedit,name='psedit'),
    path('revdel/<int:id>',views.revdel,name='revdel'),
]

app1/urls.py
from django.urls import path
from . import views
app_name='app1'
urlpatterns=[
    path('',views.index,name='index'),
    path('signup',views.signup,name='signup'),
    path('about',views.about,name='about'),
    path('service',views.service,name='service'),
    path('login',views.login,name='login'),
    path('loginhome/<int:id>',views.loginhome,name='loginhome'),
    path('signuphome',views.signuphome,name='signuphome'),
    path('careers',views.careers,name='careers'),
    path('careersignup',views.careersignup,name='careersignup'),
    path('clogin',views.clogin,name='clogin'),
    path('chome/<int:id>',views.chome,name='chome'),
    path('contact',views.contact,name='contact'),
    path('mail',views.mail,name='mail'),
    path('logout',views.logout,name='logout'),
    path('changepassword/<int:id>',views.changepassword,name='changepassword'),
    path('cupdate/<int:id>',views.cupdate,name='cupdate'),
]

adminapp/models.py
from django.db import models

# Create your models here.

# Admin login model
class AdminPage(models.Model):
    UserId=models.CharField(max_length=15)
    Password=models.CharField(max_length=15)

# Adding job model
class Job(models.Model):
    Title=models.CharField(max_length=40)
    Location=models.CharField(max_length=20)
    Decsription=models.CharField(max_length=200)
    Date=models.DateField()

# Team model
class Team(models.Model):
    Image=models.ImageField(upload_to='media/',null=True,blank=True)
    Name=models.CharField(max_length=20)
    Designation=models.CharField(max_length=20)

# Course model
class Course(models.Model):
    Photo=models.ImageField(upload_to='media/',null=True,blank=True)
    Course=models.CharField(max_length=20)
    Name=models.CharField(max_length=20)

# Review model
class Review(models.Model):
    Review=models.CharField(max_length=200)
    Photo=models.ImageField(upload_to='media/',null=True,blank=True)
    Name=models.CharField(max_length=20)
    CompanyName=models.CharField(max_length=30)

# Project Summary
class ProjectSummary(models.Model):
    Image=models.ImageField(upload_to='media/',null=True,blank=True)
    OGP=models.IntegerField()
    CP=models.IntegerField()
    SL=models.IntegerField()
    HC=models.IntegerField()

app1/models.py
from django.db import models

# Create your models here.

# Client Service Signup
class ServiceSigup(models.Model):
    Name=models.CharField(max_length=16)
    Designation=models.CharField(max_length=16)
    CompanyName=models.CharField(max_length=20)
    ContactEmail=models.EmailField()
    ContactNumber=models.IntegerField()
    ServiceType=models.CharField(max_length=15)
    ServiceDetails=models.CharField(max_length=200)
    Password=models.CharField(max_length=8)

# Job seekers signup
class CareerSignup(models.Model):
    Name=models.CharField(max_length=16)
    Email=models.EmailField()
    ContactNumber=models.IntegerField()
    DOB=models.DateField()
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    Gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    Qualification=models.CharField(max_length=20)
    InstituteName=models.CharField(max_length=20)
    YearOfPassing=models.IntegerField()
    Password=models.CharField(max_length=8)

adminapp/forms.py
from django import forms
from .models import AdminPage,Job,Team,Course,Review,ProjectSummary
from app1.models import ServiceSigup,CareerSignup

# Admin page
class AdminPageForm(forms.ModelForm):
    Password=forms.CharField(widget=forms.PasswordInput,max_length=15)
    class Meta():
        model=AdminPage
        fields=('UserId','Password')


# Client's Update for admin
class SUpdate(forms.ModelForm):
    class Meta():
        model=ServiceSigup
        fields='__all__'

# Career Update for admin
class ACUpdate(forms.ModelForm):
    class Meta():
        model=CareerSignup
        fields='__all__'

# Add job
class Addjob(forms.ModelForm):
    class Meta():
        model=Job
        fields='__all__'

# Adding team
class AddTeam(forms.ModelForm):
    class Meta():
        model=Team
        fields='__all__'

# Adding team
class AddCourse(forms.ModelForm):
    class Meta():
        model=Course
        fields='__all__'
    
# Job Edit for admin
class JobEdit(forms.ModelForm):
    class Meta():
        model=Job
        fields='__all__'

# Adding Review
class AddReview(forms.ModelForm):
    class Meta():
        model=Review
        fields='__all__'

# Team Edit for admin
class TeamEdit(forms.ModelForm):
    class Meta():
        model=Team
        fields='__all__'

# Team Edit for admin
class CourseEdit(forms.ModelForm):
    class Meta():
        model=Course
        fields='__all__'

# Review edit for admin
class ReviewEdit(forms.ModelForm):
    class Meta():
        model=Review
        fields='__all__'

# Project Summary edit for admin
class PSEdit(forms.ModelForm):
    class Meta():
        model=ProjectSummary
        fields='__all__'

adminapp/views.py
from django.http import HttpResponse
from django.shortcuts import render,redirect
from django.contrib import messages
from . forms import AdminPageForm,SUpdate,ACUpdate,Addjob,AddTeam,AddCourse,JobEdit,AddReview,TeamEdit,CourseEdit,ReviewEdit,PSEdit
from . models import AdminPage,Job,Team,Course,Review,ProjectSummary
from app1.models import ServiceSigup,CareerSignup
from MyProject import settings

# Create your views here.

# admin login
def adminlogin(request):
    if request.method=='POST':
        form=AdminPageForm(request.POST)
        if form.is_valid():
            email=form.cleaned_data['UserId']
            password=form.cleaned_data['Password']
        try:
            # checking availablity of the user
            user=AdminPage.objects.get(UserId=email)

            # checking whether the email exists or not
            if not user:
                messages.warning(request,"User does not exist")
                return redirect('/adminlogin')
            
            
            # checking whether the password is correct or not
            elif password!=user.Password:
                messages.warning(request,"Incorrect Password")
                return redirect('/adminlogin')
            
            else:
                messages.warning(request,"Login success")
                return redirect('/adminloginhome/%s'%user.id)
        except:
            messages.warning(request,"Userid or password error")
    else:
        form=AdminPageForm()
    return render(request,'adminlogin.html',{'form':form})

# adminloginhome
def adminloginhome(request):
    users=ServiceSigup.objects.all()
    users1=CareerSignup.objects.all()
    job=Job.objects.all()
    team=Team.objects.all()
    course=Course.objects.all()
    review=Review.objects.all()
    project=ProjectSummary.objects.all()
    return render(request,'adminloginhome.html',{'users':users,'users1':users1,'job':job,'team':team,'course':course,'review':review,'project':project})

# delete controll access for admin(clients)
def delete(request,id):
    user=ServiceSigup.objects.get(id=id)
    user.delete()
    messages.warning(request,"Removed successfully !")
    return redirect('/adminloginhome/1')

# delete controll access for admin (career)
def delete1(request,id):
    user=CareerSignup.objects.get(id=id)
    user.delete()
    messages.warning(request,"Removed successfully !")
    return redirect('/adminloginhome/1')

# admin update (client's details)
def supdate(request,id):
    user=ServiceSigup.objects.get(id=id)
    if request.method=='POST':
        form=SUpdate(request.POST or None, instance=user)
        if form.is_valid():
            form.save()
            messages.warning(request,"Update Successful !")
            return redirect('/adminloginhome/1')
    else:
      form=SUpdate(instance=user)
    return render(request,'supdate.html',{'form':form,'user':user})


# admin update (career details)
def acupdate(request,id):
    user=CareerSignup.objects.get(id=id)
    if request.method=='POST':
        form=ACUpdate(request.POST or None, instance=user)
        if form.is_valid():
            form.save()
            messages.warning(request,"Update Successful")
            return redirect('/adminloginhome/1')
    else:
      form=ACUpdate(instance=user)
    return render(request,'acupdate.html',{'form':form,'user':user})

# Job add page
def addjob(request):
    if request.method=='POST':
        form=Addjob(request.POST)
        if form.is_valid():
            title=form.cleaned_data['Title']
            location=form.cleaned_data['Location']
            description=form.cleaned_data['Decsription']
            date=form.cleaned_data['Date']

            tab=Job(Title=title,Location=location,Decsription=description,Date=date)
            tab.save()
            messages.warning(request,"Job added Successfully")
            return redirect('/adminloginhome/1')
    else:
        form=Addjob()
    return render(request,'addjob.html',{'form':form})

# Team details adding page
def addteam(request):
    if request.method=='POST':
        form=AddTeam(request.POST or None,request.FILES or None)
        if form.is_valid():
            image=form.cleaned_data['Image']
            name=form.cleaned_data['Name']
            designation=form.cleaned_data['Designation']

            tab=Team(Image=image,Name=name,Designation=designation)
            tab.save()
            messages.warning(request,"Team updated Successfully !")
            return redirect('/adminloginhome/1')
    
    else:
        form=AddTeam()
    return render(request,'addteam.html',{'form':form})

# delete controll access for admin (career)
def jobdelete(request,id):
    user=Job.objects.get(id=id)
    user.delete()
    messages.warning(request,"Removed successfully")
    return redirect('/adminloginhome/1')

# Add course page
def addcourse(request):
    if request.method=='POST':
        form=AddCourse(request.POST or None,request.FILES or None)
        if form.is_valid():
            photo=form.cleaned_data['Photo']
            course=form.cleaned_data['Course']
            name=form.cleaned_data['Name']

            tab=Course(Photo=photo,Course=course,Name=name)
            tab.save()
            messages.warning(request,"Course Added Successfully !")
            return redirect('/adminloginhome/1')
        
    else:
        form=AddCourse()
    return render(request,'addcourse.html',{'form':form})

# Job edit page
def jobedit(request,id):
    user=Job.objects.get(id=id)
    if request.method=='POST':
        form=JobEdit(request.POST or None, instance=user)
        if form.is_valid():
            form.save()
            messages.warning(request,"Job Updated Successfully")
            return redirect('/adminloginhome/1')
    else:
      form=JobEdit(instance=user)
    return render(request,'jobedit.html',{'form':form,'user':user})

# review adding page
def addreview(request):
    if request.method=='POST':
        form=AddReview(request.POST or None,request.FILES or None)
        if form.is_valid():
            review=form.cleaned_data['Review']
            photo=form.cleaned_data['Photo']
            name=form.cleaned_data['Name']
            cname=form.cleaned_data['CompanyName']

            tab=Review(Review=review,Photo=photo,Name=name,CompanyName=cname)
            tab.save()
            messages.warning(request,"Review Added Successfully !")
            return redirect('/adminloginhome/1')
        
    else:
        form=AddReview()
    return render(request,'addreview.html',{'form':form})

# Team edit page
def teamedit(request,id):
    user=Team.objects.get(id=id)
    if request.method=='POST':
        form=TeamEdit(request.POST or None,request.FILES,  instance=user)
        if form.is_valid():
            form.save()
            messages.warning(request,"Team Updated Successfully")
            return redirect('/adminloginhome/1')
    else:
      form=TeamEdit(instance=user)
    return render(request,'teamedit.html',{'form':form,'user':user})

# Team delete control
def teamdel(request,id):
    user=Team.objects.get(id=id)
    user.delete()
    messages.warning(request,"Removed successfully")
    return redirect('/adminloginhome/1')


# Course edit page
def courseedit(request,id):
    user=Course.objects.get(id=id)
    if request.method=='POST':
        form=CourseEdit(request.POST or None,request.FILES, instance=user)
        if form.is_valid():
            form.save()
            messages.warning(request,"Course Updated Successfully")
            return redirect('/adminloginhome/1')
    else:
      form=CourseEdit(instance=user)
    return render(request,'courseedit.html',{'form':form,'user':user})

# Course delete control
def coursedel(request,id):
    user=Course.objects.get(id=id)
    user.delete()
    messages.warning(request,"Removed successfully")
    return redirect('/adminloginhome/1')

# Review edit page
def reviewedit(request,id):
    user=Review.objects.get(id=id)
    if request.method=='POST':
        form=ReviewEdit(request.POST or None,request.FILES, instance=user)
        if form.is_valid():
            form.save()
            messages.warning(request,"Review Updated Successfully !")
            return redirect('/adminloginhome/1')
    else:
        form=ReviewEdit(instance=user)
    return render(request,'reviewedit.html',{'form':form})

# admin update (career details)
def psedit(request,id):
    user=ProjectSummary.objects.get(id=id)
    if request.method=='POST':
        form=PSEdit(request.POST or None,request.FILES, instance=user)
        if form.is_valid():
            form.save()
            messages.warning(request,"Update Successful")
            return redirect('/adminloginhome/1')
    else:
      form=PSEdit(instance=user)
    return render(request,'psedit.html',{'form':form,'user':user})

# Review delete page
def revdel(request,id):
    user=Review.objects.get(id=id)
    user.delete()
    messages.warning(request,"Removed successfully")
    return redirect('/adminloginhome/1')

adminapp/templates/acupdate.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ADMIN CONTROL</title>
    <link rel="stylesheet" href="{% static 'css/careersgnp.css' %}">
</head>
<body>
    <div class="crr-body">
            <section class="career-sgnp">

      <header>Admin Control</header>
      <div class="sgnp-alt">
        {% for msg in messages %}
        {{msg}}
        {% endfor %}
        </div>
  
    <form class=" formi" action="" method="POST">
        {% csrf_token %}
        <div class="input-box">
    
    <label for="id_Name">Name</label>
    <input type="text" name="Name" maxlength="16" required id="id_Name" value="{{user.Name}}">
        </div>
    
        <div class="input-box">

    <label for="id_Email">Email</label>
    <input type="email" name="Email" maxlength="254" required id="id_Email" value="{{user.Email}}"></div>

        <div class="input-box">
    
    <label for="id_ContactNumber">Contact Number</label>
    <input type="number" name="ContactNumber" required id="id_ContactNumber" value="{{user.ContactNumber}}">
        </div>     
        <div class="column">

            <div class="gender-box">
                <label for="id_Gender" style="color: #333;">Gender</label>
                <select name="Gender" required id="id_Gender" class="slt-box" value="{{user.Gender}}" style="border-radius: 6px;
                margin-top: 5px;
                padding: 0 105px;
                outline: none;
                font-size: 1rem;
                color: #707070;
                border: 1px solid #ddd;
                height: 55px;
                width: 19rem;">
                <option value="" selected>Gender</option>
                <option value="M">Male</option>
                <option value="F">Female</option>
                </select>
            </div>

        <!-- <div class="input-box">

    <label for="id_DOB">DOB</label>
    <input type="date" name="date" required id="id_DOB" value="{{user.DOB}}">

        </div> -->
        </div>



          <div class="input-box">
      
    <label for="id_Qualification">Qualification</label>
    <input type="text" name="Qualification" maxlength="20" required id="id_Qualification" value="{{user.Qualification}}">
          </div>

        <div class="input-box">

    <label for="id_InstituteName">Institute  Name</label>    
    <input type="text" name="InstituteName" maxlength="20" required id="id_InstituteName" value="{{user.InstituteName}}">

        </div>
    
        <div class="input-box">

    <label for="id_YearOfPassing">Year Of Passing</label>  
    <input type="number" name="YearOfPassing" required id="id_YearOfPassing" value="{{user.YearOfPassing}}">
      
        </div>

        <div class="input-box">

    <label for="id_Password">Password</label> 
    <input type="password" name="Password" maxlength="8" minlength="6" required id="id_Password" value="{{user.Password}}">
        </div>

    <input  type="submit" class="submit-btn" value="Save">
    </form>

    </section>
    </div>

</body>
</html>

adminapp/templates/addjob.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Add Job</title>
    <!-- custom css file -->
    <link rel="stylesheet" href="{% static 'css/cpw.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>


</head>
<body>
    
  <form class="formi" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <section class="container forms" style="margin-top: 3em;">
            <div class="form login">
                <div class="form-content">
                    <header>Admin Course Add</header>
                    <form action="#">
                        <div class="field input-field">
                          <input type="text" name="Title" placeholder="Title" maxlength="40" required id="id_Title">
                        </div>
  
                        <div class="field input-field">
                          <input type="text" name="Location" placeholder="Location" maxlength="20" required id="id_Location">
                        </div>
                        <div class="field input-field">
                          <input type="text" name="Decsription" placeholder="Description" maxlength="200" required id="id_Decsription">
                        </div>
  
                        <div class="field input-field">
                          <input type="date" name="Date"  required id="id_Date">
                        </div>
                        {% for msg in messages %}
                        <div class="alrt-msg">
                          <div class="alert alert-warning alert-dismissible fade show" role="alert">
                            <strong></strong> {{ msg }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                          </div>
                        {% endfor %}
  
                        </div>
  
                        <div class="field button-field">
                          <input class="lg-btn"  type="submit" value="Save">
  
                        </div>
                    </form>
                </div>
  
            </div>
  
           
        </section>
      </form>
  </body>
</html>

adminapp/templates/addreview.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- custom css file -->
    <link rel="stylesheet" href="{% static 'css/cpw.css' %}">

</head>
<body>
    <form class="formi" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            <section class="container forms" style="margin-top: 3em;">
                <div class="form login">
                    <div class="form-content">
                        <header>Admin Review Add</header>
                        <form action="#">
                            <div class="field input-field">
                                <input type="text" name="Review" placeholder="Review" maxlength="200" required id="id_Review">
                            </div>
                            <div class="field input-field">
                                <input type="file" name="Photo" accept="image/*" id="id_Photo"
                                style="padding-top: 13px;
                                padding-left: 25px;">
                            </div>
    
                            <div class="field input-field">
                                <input type="text" name="Name" placeholder="Name" maxlength="20" required id="id_Name">
                            </div>
                            <div class="field input-field">
                                <input type="text" name="CompanyName" placeholder="Company Name" maxlength="30" required id="id_CompanyName">
                            </div>
    
                            <div class="alrt-msg">
                            {% for msg in messages %}
                            {{ msg }}
                            {% endfor %}
    
                            </div>
    
                            <div class="field button-field">
                              <input class="lg-btn"  type="submit" value="Save">
    
                            </div>
                        </form>
                    </div>
    
                </div>
    
               
            </section>
          </form></body>
</html>

adminapp/templates/jobedit.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Add Job</title>
    <!-- custom css file -->
    <link rel="stylesheet" href="{% static 'css/cpw.css' %}">

</head>
<body>
    
  <form class="formi" action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
        <section class="container forms" style="margin-top: 3em;">
            <div class="form login">
                <div class="form-content">
                    <header>Admin Job Edit</header>
                    <form action="#">
                        <div class="field input-field">
                          <input type="text" name="Title" value="{{user.Title}}" maxlength="40" required id="id_Title">
                        </div>
  
                        <div class="field input-field">
                          <input type="text" name="Location" value="{{user.Location}}" maxlength="20" required id="id_Location">
                        </div>
                        <div class="field input-field">
                          <input type="text" name="Decsription" value="{{user.Decsription}}" maxlength="200" required id="id_Decsription">
                        </div>
  
                        <div class="field input-field">
                          <input type="date" name="Date" required id="id_Date">
                        </div>
  
                        <div class="alrt-msg">
                        {% for msg in messages %}
                        {{ msg }}
                        {% endfor %}
  
                        </div>
  
                        <div class="field button-field">
                          <input class="lg-btn"  type="submit" value="Save">
  
                        </div>
                    </form>
                </div>
  
            </div>
  
           
        </section>
      </form>
  </body>
</html>

adminapp/templates/psedit.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin </title>
    <!-- custom css file -->
    <link rel="stylesheet" href="{% static 'css/cpw.css' %}">
</head>
<body>
    <form class="formi" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
            <section class="container forms" style="margin-top: 3em;">
                <div class="form login">
                    <div class="form-content">
                        <header>Admin Job Edit</header>
                        <form action="#">
                            <div class="field input-field">
                                <input type="file" name="Image" accept="image/*" id="id_Image" style="padding-top: 13px;padding-left: 25px;">
                            </div>
                            <div class="field input-field">
                                <input type="number" name="OGP" value="123" required id="id_OGP">
                            </div>
      
                            <div class="field input-field">
                                <input type="number" name="CP" value="1234" required id="id_CP">
                            </div>
                            <div class="field input-field">
                                <input type="number" name="SL" value="123" required id="id_SL">
                            </div>
      
                            <div class="field input-field">
                                <input type="number" name="HC" value="1234" required id="id_HC">
                            </div>
      
                            <div class="alrt-msg">
                            {% for msg in messages %}
                            {{ msg }}
                            {% endfor %}
      
                            </div>
      
                            <div class="field button-field">
                              <input class="lg-btn"  type="submit" value="Save">
      
                            </div>
                        </form>
                    </div>
      
                </div>
      
               
            </section>
          </form>
    </body>
</html>

adminapp/templates/supdate.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MNC PORTFOLIO</title>
    
    <!-- custom css file -->
    <link rel="stylesheet" href="{% static 'css/cpw.css' %}">
  </head>
 <body>

  <form class="formi" action="" method="POST">
    {% csrf_token %}
        <section class="container forms" style="margin-top: 3em;">
            <div class="form login">
                <div class="form-content">
                    <header>Admin Control</header>
                    <form action="#">
                        <div class="field input-field">
                            <input type="text" name="Name" value="{{user.Name}}"   maxlength="16" required id="id_Name">
                        </div>

                        <div class="field input-field">
                            <input type="text" name="Designation" value="{{user.Designation}}"  maxlength="16" required id="id_Designation">
                           
                        </div>
                        <div class="field input-field">
                            <input type="text" name="CompanyName" value="{{user.CompanyName}}"   maxlength="20" required id="id_CompanyName">
                        </div>

                        <div class="field input-field">
                            <input type="email" name="ContactEmail" value="{{user.ContactEmail}}"  maxlength="254" required id="id_ContactEmail">
                        </div>

                        <div class="field input-field">
                            <input type="number" name="ContactNumber" value="{{user.ContactNumber}}"  required id="id_ContactNumber">
                        </div>

                        <div class="field input-field">
                            <input type="text" name="ServiceType" value="{{user.ServiceType}}"   maxlength="15" required id="id_ServiceType">
                        </div>

                        <div class="field input-field">
                            <input type="text" name="ServiceDetails" value="{{user.ServiceDetails}}"   maxlength="200" required id="id_ServiceDetails">
                        </div>

                        <div class="field input-field">
                            <input type="text" name="Password" value="{{user.Password}}"   maxlength="8" required id="id_Password">
                        </div>

                        <div class="alrt-msg">
                        {% for msg in messages %}
                        {{ msg }}
                        {% endfor %}

                        </div>

                        <div class="field button-field">
                          <input class="lg-btn"  type="submit" value="Save">

                        </div>
                    </form>
                </div>

            </div>

           
        </section>
      </form>

        
    </body>
</html>